name: Deploy Lambda Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Zipping conversion_of_mp4_to_mp3
      run: |
        cd conversion_of_mp4_to_mp3.py
        zip -r ../conversion_of_mp4_to_mp3.zip .
        cd ..

    - name: Deploy conversion_of_mp4_to_mp3
      run: |
        aws lambda update-function-code --function-name conversion_of_mp4_to_mp3 --zip-file fileb://conversion_of_mp4_to_mp3.zip

    - name: Zipping conversion_of_mp3_to_json
      run: |
        cd conversion_of_mp3_to_json.py
        zip -r ../conversion_of_mp3_to_json.zip .
        cd ..

    - name: Deploy conversion_of_mp3_to_json
      run: |
        aws lambda update-function-code --function-name conversion_of_mp3_to_json --zip-file fileb://conversion_of_mp3_to_json.zip
    
    - name: Zipping json_to_cloudsearch
      run: |
        cd json_to_cloudsearch.py
        zip -r ../json_to_cloudsearch.zip .
        cd ..

    - name: Deploy json_to_cloudsearch
      run: |
        aws lambda update-function-code --function-name json_to_cloudsearch --zip-file fileb://json_to_cloudsearch.zip

    - name: Zipping api_to_lambda
      run: |
        cd api_to_lambda.py
        zip -r ../api_to_lambda.zip .
        cd ..

    - name: Deploy api_to_lambda
      run: |
        aws lambda update-function-code --function-name api_to_lambda --zip-file fileb://api_to_lambda.zip
